[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
test = "test"

remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
monad-testnet = "https://monad-testnet.drpc.org"
monad-mainnet = "https://monad-mainnet.drpc.org"

[etherscan]
monad-mainnet = { key = "${MONAD_EXPLORER_KEY}", url = "https://explorer.monad.xyz/api" }
monad-testnet = { key = "${MONAD_EXPLORER_KEY}", url = "https://testnet.explorer.monad.xyz/api" }
