[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC}"
monad_mainnet = "${MONAD_MAINNET_RPC}"

[etherscan]
monad_testnet = { key = "${MONAD_EXPLORER_KEY}", url = "https://testnet.monadexplorer.xyz/api" }
