[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
hyperliquid-mainnet = "https://rpc.hyperliquid.xyz/evm"
hyperliquid-testnet = "https://rpc.hyperliquid-testnet.xyz/evm"

[etherscan]
hyperliquid = { key = "${HYPERLIQUID_EXPLORER_KEY}", url = "https://explorer.hyperliquid.xyz/api" }
