[profile.default]
src = "."
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad-testnet = "${MONAD_TESTNET_RPC}"
monad-mainnet = "${MONAD_MAINNET_RPC}"

[etherscan]
monad = { key = "${MONAD_EXPLORER_KEY}", url = "https://explorer.monad.xyz/api" }
