services:
    eliza:
        image: aikamiyo/eliza:latest
        stdin_open: true
        tty: true
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY:-}
        ports:
            - "3001:3000"
            - "5173:5173"
        restart: unless-stopped
volumes:
    eliza:



